import {
  BadgeDollarSign,
  BadgePercent,
  ChartNoAxesCombined,
  CircleDotDashed,
  House,
  LayoutDashboard,
  PackageSearch,
  ScrollText,
  Shapes,
  SlidersHorizontal,
  TableProperties,
  UserCog,
  WalletCards,
  Warehouse,
  type LucideIcon,
} from "lucide-react";

/** Iconos de navegación centralizados (lucide-react) para mantener consistencia visual. */
export const NAV_ICONS = {
  home: House,
  quickSale: BadgeDollarSign,
  tables: TableProperties,
  billiard: CircleDotDashed,
  inventory: Warehouse,
  products: PackageSearch,
  categories: Shapes,
  promotions: BadgePercent,
  cash: WalletCards,
  reports: ChartNoAxesCombined,
  audit: ScrollText,
  users: UserCog,
  settings: SlidersHorizontal,
  administration: LayoutDashboard,
} satisfies Record<string, LucideIcon>;
